"""
Comprehensive medical knowledge base for the RAG system.
Contains reference ranges, clinical significance, symptom correlations,
and condition patterns for common lab tests.
"""

MEDICAL_KNOWLEDGE = [
    # ─── COMPLETE BLOOD COUNT (CBC) ───────────────────────────────────────────
    {
        "id": "cbc_wbc",
        "category": "CBC",
        "test": "White Blood Cell Count (WBC)",
        "normal_range": "4.5–11.0 × 10³/µL",
        "low_significance": "Leukopenia. Can indicate bone marrow suppression, viral infections (HIV, hepatitis), autoimmune conditions (lupus), or certain medications (chemotherapy, immunosuppressants). Increases infection risk.",
        "high_significance": "Leukocytosis. Common with bacterial infections, inflammatory conditions, stress response, corticosteroids, leukemia, or smoking. Very high values (>30,000) may indicate leukemia.",
        "critical_low": "< 2.0 × 10³/µL — High risk of severe infection",
        "critical_high": "> 30.0 × 10³/µL — Possible leukemia workup needed",
        "symptoms_associated": ["fever", "fatigue", "recurrent infections", "night sweats", "easy bruising"],
        "conditions": ["infection", "leukemia", "lupus", "HIV", "immunosuppression"],
        "plain_english": "This measures your infection-fighting white blood cells. Too few means reduced immune defense; too many usually signals your body is fighting something.",
    },
    {
        "id": "cbc_rbc",
        "category": "CBC",
        "test": "Red Blood Cell Count (RBC)",
        "normal_range": "Men: 4.7–6.1 × 10⁶/µL | Women: 4.2–5.4 × 10⁶/µL",
        "low_significance": "Anemia. Can result from iron deficiency, B12/folate deficiency, chronic disease, blood loss, kidney disease, or bone marrow disorders.",
        "high_significance": "Polycythemia. Seen with dehydration, high altitude adaptation, lung disease, smoking, or polycythemia vera (blood cancer).",
        "conditions": ["anemia", "polycythemia vera", "COPD", "kidney disease"],
        "symptoms_associated": ["fatigue", "shortness of breath", "pale skin", "dizziness", "cold hands"],
        "plain_english": "Red blood cells carry oxygen throughout your body. Low counts cause fatigue and breathlessness; high counts can thicken the blood.",
    },
    {
        "id": "cbc_hemoglobin",
        "category": "CBC",
        "test": "Hemoglobin (Hgb/Hb)",
        "normal_range": "Men: 13.5–17.5 g/dL | Women: 12.0–15.5 g/dL",
        "low_significance": "Anemia. Causes include iron deficiency (most common), blood loss, hemolysis, chronic disease, B12/folate deficiency, kidney disease. Symptoms worsen below 8 g/dL.",
        "high_significance": "Dehydration, COPD, high altitude, polycythemia vera, smoking.",
        "critical_low": "< 7 g/dL — Transfusion may be needed",
        "critical_high": "> 20 g/dL — Hyperviscosity risk",
        "conditions": ["iron deficiency anemia", "pernicious anemia", "thalassemia", "sickle cell", "COPD"],
        "symptoms_associated": ["extreme fatigue", "weakness", "pale skin", "shortness of breath", "chest pain", "headache"],
        "plain_english": "Hemoglobin is the protein in red cells that carries oxygen. It's the most important anemia marker — low values are why you feel tired and short of breath.",
    },
    {
        "id": "cbc_hematocrit",
        "category": "CBC",
        "test": "Hematocrit (Hct)",
        "normal_range": "Men: 41–53% | Women: 36–46%",
        "low_significance": "Anemia, blood loss, overhydration.",
        "high_significance": "Dehydration, polycythemia, COPD.",
        "conditions": ["anemia", "polycythemia", "dehydration"],
        "symptoms_associated": ["fatigue", "dizziness", "shortness of breath"],
        "plain_english": "The percentage of your blood made up of red cells. Works alongside hemoglobin to confirm anemia or polycythemia.",
    },
    {
        "id": "cbc_mcv",
        "category": "CBC",
        "test": "Mean Corpuscular Volume (MCV)",
        "normal_range": "80–100 fL",
        "low_significance": "Microcytic anemia — iron deficiency, thalassemia, lead poisoning, chronic disease anemia.",
        "high_significance": "Macrocytic anemia — B12 deficiency, folate deficiency, hypothyroidism, liver disease, alcoholism, certain medications (methotrexate, hydroxyurea).",
        "conditions": ["iron deficiency", "B12 deficiency", "folate deficiency", "thalassemia", "alcoholism"],
        "symptoms_associated": ["fatigue", "numbness", "memory problems", "mouth sores"],
        "plain_english": "The size of your red blood cells. Small cells suggest iron deficiency; large cells point to B12 or folate problems or alcohol use.",
    },
    {
        "id": "cbc_platelets",
        "category": "CBC",
        "test": "Platelet Count (PLT)",
        "normal_range": "150,000–400,000/µL",
        "low_significance": "Thrombocytopenia — increased bleeding risk. Causes: ITP, lupus, heparin-induced, liver disease, bone marrow disorders, viral infections (dengue, HIV), medications.",
        "high_significance": "Thrombocytosis — clot risk. Reactive (infection, inflammation, iron deficiency) or essential thrombocythemia.",
        "critical_low": "< 50,000/µL — Significant bleeding risk; < 20,000/µL — Spontaneous bleeding risk",
        "critical_high": "> 1,000,000/µL — Thrombosis and bleeding risk",
        "conditions": ["ITP", "liver disease", "leukemia", "essential thrombocythemia"],
        "symptoms_associated": ["easy bruising", "petechiae", "prolonged bleeding", "nosebleeds", "gum bleeding"],
        "plain_english": "Platelets form clots to stop bleeding. Too few means you bruise and bleed easily; too many can cause dangerous clots.",
    },
    {
        "id": "cbc_neutrophils",
        "category": "CBC",
        "test": "Neutrophils (Absolute Neutrophil Count)",
        "normal_range": "1.8–7.7 × 10³/µL (50–70% of WBC)",
        "low_significance": "Neutropenia — severe infection risk. Causes: chemotherapy, aplastic anemia, viral infections, autoimmune conditions.",
        "high_significance": "Neutrophilia — bacterial infection, stress, corticosteroids, smoking.",
        "critical_low": "< 0.5 × 10³/µL — Severe neutropenia, high infection risk",
        "conditions": ["bacterial infection", "chemotherapy effects", "aplastic anemia"],
        "symptoms_associated": ["recurrent bacterial infections", "fever"],
        "plain_english": "Your first-line bacterial infection fighters. Critically low counts after chemotherapy mean you need protective precautions.",
    },
    {
        "id": "cbc_lymphocytes",
        "category": "CBC",
        "test": "Lymphocytes",
        "normal_range": "1.0–4.8 × 10³/µL (20–40% of WBC)",
        "low_significance": "Lymphopenia — seen with HIV, immunosuppression, corticosteroids, severe infections, malnutrition.",
        "high_significance": "Lymphocytosis — viral infections (mono, CMV), CLL, pertussis.",
        "conditions": ["HIV", "viral infections", "CLL", "autoimmune disease"],
        "symptoms_associated": ["recurrent infections", "swollen lymph nodes", "fatigue"],
        "plain_english": "Lymphocytes fight viral infections and produce antibodies. Very low counts suggest immune system problems.",
    },

    # ─── COMPREHENSIVE METABOLIC PANEL (CMP) ────────────────────────────────
    {
        "id": "cmp_glucose",
        "category": "CMP/Metabolic",
        "test": "Glucose (Fasting Blood Sugar)",
        "normal_range": "70–99 mg/dL (fasting) | < 140 mg/dL (2-hr postprandial)",
        "low_significance": "Hypoglycemia — insulin overdose, fasting, liver disease, adrenal insufficiency, insulinoma. Symptoms below 70 mg/dL.",
        "high_significance": "Hyperglycemia — diabetes mellitus, prediabetes, stress, medications (steroids), Cushing's syndrome, pancreatitis.",
        "critical_low": "< 40 mg/dL — Medical emergency",
        "critical_high": "> 500 mg/dL — DKA/HHS risk",
        "conditions": ["type 2 diabetes", "prediabetes", "type 1 diabetes", "metabolic syndrome", "Cushing's syndrome"],
        "symptoms_associated": ["frequent urination", "excessive thirst", "blurred vision", "fatigue", "slow wound healing", "shakiness", "sweating"],
        "plain_english": "Blood sugar level. Persistently high values indicate prediabetes or diabetes. Low values can cause shakiness, confusion, and fainting.",
    },
    {
        "id": "cmp_bun",
        "category": "CMP/Kidney",
        "test": "Blood Urea Nitrogen (BUN)",
        "normal_range": "7–20 mg/dL",
        "low_significance": "Liver disease, malnutrition, overhydration.",
        "high_significance": "Kidney dysfunction, dehydration, high protein diet, GI bleeding, muscle breakdown (rhabdomyolysis).",
        "critical_high": "> 100 mg/dL — Severe kidney impairment",
        "conditions": ["chronic kidney disease", "acute kidney injury", "dehydration", "liver failure"],
        "symptoms_associated": ["swelling", "fatigue", "decreased urination", "nausea", "confusion"],
        "plain_english": "A waste product from protein breakdown filtered by kidneys. High levels suggest kidneys aren't filtering properly.",
    },
    {
        "id": "cmp_creatinine",
        "category": "CMP/Kidney",
        "test": "Creatinine",
        "normal_range": "Men: 0.74–1.35 mg/dL | Women: 0.59–1.04 mg/dL",
        "low_significance": "Low muscle mass, severe liver disease.",
        "high_significance": "Kidney disease (most common), dehydration, muscle damage, certain medications (NSAIDs, ACE inhibitors, some antibiotics).",
        "critical_high": "> 10 mg/dL — Dialysis may be needed",
        "conditions": ["CKD", "acute kidney injury", "rhabdomyolysis", "diabetic nephropathy"],
        "symptoms_associated": ["decreased urination", "swollen ankles", "fatigue", "nausea", "shortness of breath", "confusion"],
        "plain_english": "The most important kidney function marker. Creatinine is muscle waste filtered by kidneys — rising levels mean kidneys are struggling.",
    },
    {
        "id": "cmp_egfr",
        "category": "CMP/Kidney",
        "test": "eGFR (Estimated Glomerular Filtration Rate)",
        "normal_range": "> 60 mL/min/1.73m²",
        "low_significance": "Kidney function stages: G1 (≥90, normal/high), G2 (60–89, mildly decreased), G3a (45–59, mild-moderately decreased), G3b (30–44, moderately-severely decreased), G4 (15–29, severely decreased), G5 (<15, kidney failure).",
        "high_significance": "Not clinically significant unless very high (possible hyperfiltration in early diabetes).",
        "critical_low": "< 15 mL/min — Kidney failure, dialysis consideration",
        "conditions": ["CKD stages 1–5", "diabetic nephropathy", "hypertensive nephropathy"],
        "symptoms_associated": ["edema", "fatigue", "decreased urine output", "foamy urine"],
        "plain_english": "Estimates how well your kidneys filter blood per minute. Below 60 for 3+ months means chronic kidney disease — the lower the number, the more serious.",
    },
    {
        "id": "cmp_sodium",
        "category": "CMP/Electrolytes",
        "test": "Sodium (Na⁺)",
        "normal_range": "136–145 mEq/L",
        "low_significance": "Hyponatremia — excessive fluid intake, SIADH, heart failure, liver cirrhosis, hypothyroidism, Addison's disease, diuretics. Can cause brain swelling.",
        "high_significance": "Hypernatremia — dehydration, diabetes insipidus, excessive sodium intake, fever. Can cause brain shrinkage.",
        "critical_low": "< 120 mEq/L — Risk of seizures and coma",
        "critical_high": "> 160 mEq/L — Severe neurological risk",
        "conditions": ["SIADH", "heart failure", "cirrhosis", "dehydration", "Addison's disease"],
        "symptoms_associated": ["nausea", "headache", "confusion", "seizures", "fatigue", "muscle cramps"],
        "plain_english": "Sodium regulates fluid balance. Low levels can cause brain swelling; high levels from dehydration can be dangerous.",
    },
    {
        "id": "cmp_potassium",
        "category": "CMP/Electrolytes",
        "test": "Potassium (K⁺)",
        "normal_range": "3.5–5.0 mEq/L",
        "low_significance": "Hypokalemia — diuretics (most common), diarrhea/vomiting, Cushing's syndrome, low dietary intake. Causes muscle weakness and heart arrhythmias.",
        "high_significance": "Hyperkalemia — kidney disease, ACE inhibitors, potassium-sparing diuretics, tissue destruction, Addison's disease. Can cause fatal heart arrhythmias.",
        "critical_low": "< 2.5 mEq/L — Cardiac arrhythmia risk",
        "critical_high": "> 6.5 mEq/L — Cardiac emergency",
        "conditions": ["CKD", "Addison's disease", "Cushing's syndrome", "diuretic therapy"],
        "symptoms_associated": ["muscle weakness", "cramps", "palpitations", "fatigue", "constipation", "numbness"],
        "plain_english": "Critical for heart rhythm and muscle function. Abnormal potassium — in either direction — can cause dangerous heart arrhythmias.",
    },
    {
        "id": "cmp_alt",
        "category": "CMP/Liver",
        "test": "ALT (Alanine Aminotransferase / SGPT)",
        "normal_range": "Men: 7–56 U/L | Women: 7–45 U/L",
        "low_significance": "Not clinically significant.",
        "high_significance": "Liver cell damage. Causes: hepatitis (viral, alcoholic, NAFLD/NASH), medications (statins, acetaminophen, antibiotics), celiac disease, thyroid disease. ALT >3× ULN is significant. ALT >10× ULN suggests acute hepatitis or ischemia.",
        "critical_high": "> 1000 U/L — Acute liver injury or ischemia",
        "conditions": ["hepatitis B/C", "NAFLD", "alcoholic liver disease", "autoimmune hepatitis", "drug-induced liver injury"],
        "symptoms_associated": ["jaundice", "abdominal pain (right upper quadrant)", "dark urine", "fatigue", "nausea", "loss of appetite"],
        "plain_english": "The most liver-specific enzyme. Elevated ALT is the hallmark of liver inflammation or damage, often from fatty liver, alcohol, or hepatitis.",
    },
    {
        "id": "cmp_ast",
        "category": "CMP/Liver",
        "test": "AST (Aspartate Aminotransferase / SGOT)",
        "normal_range": "10–40 U/L",
        "low_significance": "Not clinically significant.",
        "high_significance": "Liver or muscle damage. AST:ALT ratio > 2:1 suggests alcoholic liver disease. Also elevated in heart attack, muscle injury, and strenuous exercise.",
        "conditions": ["liver disease", "myocardial infarction", "muscle injury", "alcoholic hepatitis"],
        "symptoms_associated": ["jaundice", "fatigue", "chest pain", "muscle pain"],
        "plain_english": "Another liver enzyme, but also found in heart and muscle. The AST/ALT ratio helps distinguish alcoholic from non-alcoholic liver disease.",
    },
    {
        "id": "cmp_alkaline_phosphatase",
        "category": "CMP/Liver",
        "test": "Alkaline Phosphatase (ALP)",
        "normal_range": "44–147 U/L",
        "low_significance": "Hypothyroidism, pernicious anemia, zinc deficiency.",
        "high_significance": "Liver disease (bile duct obstruction, cholestasis, liver metastases), bone disease (Paget's, bone metastases, healing fractures), pregnancy, growth spurts in children.",
        "conditions": ["primary biliary cholangitis", "PSC", "liver metastases", "Paget's disease", "hyperparathyroidism"],
        "symptoms_associated": ["jaundice", "itching", "bone pain", "abdominal pain"],
        "plain_english": "Elevated ALP points to bile duct problems in the liver or bone disorders. Must be interpreted with GGT and other liver tests.",
    },
    {
        "id": "cmp_bilirubin",
        "category": "CMP/Liver",
        "test": "Total Bilirubin",
        "normal_range": "0.1–1.2 mg/dL",
        "low_significance": "Not clinically significant.",
        "high_significance": "Jaundice occurs above 2.5 mg/dL. Causes: liver disease (hepatitis, cirrhosis), bile duct obstruction (gallstones, pancreatic cancer), hemolysis, Gilbert's syndrome (benign).",
        "critical_high": "> 15 mg/dL — Severe liver failure or neonatal jaundice",
        "conditions": ["hepatitis", "cirrhosis", "gallstones", "pancreatic cancer", "hemolytic anemia", "Gilbert's syndrome"],
        "symptoms_associated": ["jaundice (yellow skin/eyes)", "dark urine", "pale stools", "itching", "abdominal pain"],
        "plain_english": "A breakdown product of red blood cells processed by the liver. High levels turn skin and eyes yellow (jaundice).",
    },
    {
        "id": "cmp_albumin",
        "category": "CMP/Liver",
        "test": "Albumin",
        "normal_range": "3.4–5.4 g/dL",
        "low_significance": "Hypoalbuminemia — liver failure (production failure), malnutrition, nephrotic syndrome (protein loss), protein-losing enteropathy, chronic inflammation. Marker of chronic liver function.",
        "high_significance": "Dehydration.",
        "conditions": ["liver cirrhosis", "nephrotic syndrome", "malnutrition", "inflammatory bowel disease"],
        "symptoms_associated": ["edema", "ascites", "weakness", "poor wound healing"],
        "plain_english": "Made by the liver; albumin maintains fluid balance. Low albumin means the liver is struggling to produce protein or protein is being lost.",
    },
    {
        "id": "cmp_calcium",
        "category": "CMP/Electrolytes",
        "test": "Calcium (Total)",
        "normal_range": "8.5–10.5 mg/dL",
        "low_significance": "Hypocalcemia — hypoparathyroidism, vitamin D deficiency, magnesium deficiency, kidney disease, malabsorption. Causes muscle spasms, tetany.",
        "high_significance": "Hypercalcemia — primary hyperparathyroidism (most common), malignancy (bone metastases, PTHrP), sarcoidosis, vitamin D toxicity, thiazide diuretics.",
        "critical_low": "< 7.0 mg/dL — Tetany and seizure risk",
        "critical_high": "> 13.0 mg/dL — Hypercalcemic crisis",
        "conditions": ["hyperparathyroidism", "malignancy", "vitamin D deficiency", "hypoparathyroidism", "kidney disease"],
        "symptoms_associated": ["muscle cramps", "tetany", "bone pain", "kidney stones", "confusion", "fatigue", "constipation", "excessive thirst"],
        "plain_english": "Essential for bones, muscles, and nerves. 'Bones, stones, groans, and psychic moans' is the classic mnemonic for high calcium symptoms.",
    },

    # ─── LIPID PANEL ────────────────────────────────────────────────────────
    {
        "id": "lipid_cholesterol",
        "category": "Lipid Panel",
        "test": "Total Cholesterol",
        "normal_range": "< 200 mg/dL (desirable) | 200–239 (borderline) | ≥ 240 (high)",
        "low_significance": "Hypocholesterolemia — malnutrition, liver disease, hyperthyroidism, malabsorption.",
        "high_significance": "Hypercholesterolemia — cardiovascular disease risk. Causes: diet, genetics (familial hypercholesterolemia), hypothyroidism, diabetes, kidney disease.",
        "conditions": ["atherosclerosis", "CAD", "familial hypercholesterolemia", "hypothyroidism"],
        "symptoms_associated": ["chest pain", "xanthomas", "corneal arcus"],
        "plain_english": "The total of all cholesterol types. Elevated levels increase heart disease and stroke risk, but must be interpreted with HDL and LDL.",
    },
    {
        "id": "lipid_ldl",
        "category": "Lipid Panel",
        "test": "LDL Cholesterol (Low-Density Lipoprotein)",
        "normal_range": "< 100 mg/dL (optimal) | 100–129 (near optimal) | 130–159 (borderline high) | 160–189 (high) | ≥ 190 (very high)",
        "low_significance": "Generally good. Extremely low (< 40) may be associated with hemorrhagic stroke or cancer.",
        "high_significance": "The 'bad' cholesterol — deposits in artery walls causing plaques. Major modifiable CAD risk factor. Target varies by cardiovascular risk (< 70 for very high risk, < 100 for high risk).",
        "conditions": ["atherosclerosis", "CAD", "stroke", "peripheral artery disease"],
        "symptoms_associated": ["chest pain", "heart attack symptoms", "stroke symptoms"],
        "plain_english": "The 'bad' cholesterol that builds up in arteries. Lower is almost always better. Statins primarily work by lowering LDL.",
    },
    {
        "id": "lipid_hdl",
        "category": "Lipid Panel",
        "test": "HDL Cholesterol (High-Density Lipoprotein)",
        "normal_range": "Men: ≥ 40 mg/dL | Women: ≥ 50 mg/dL | Optimal: ≥ 60 mg/dL",
        "low_significance": "Low HDL is an independent cardiovascular risk factor. Causes: obesity, sedentary lifestyle, smoking, diabetes, insulin resistance, high triglycerides, genetic factors.",
        "high_significance": "Generally protective. Very high HDL (> 80) may paradoxically not be beneficial — some genetic forms don't reduce CV risk.",
        "conditions": ["metabolic syndrome", "CAD risk"],
        "symptoms_associated": ["no direct symptoms — risk factor"],
        "plain_english": "The 'good' cholesterol that removes bad cholesterol from arteries. Higher is better. Exercise and quitting smoking raise HDL.",
    },
    {
        "id": "lipid_triglycerides",
        "category": "Lipid Panel",
        "test": "Triglycerides",
        "normal_range": "< 150 mg/dL (normal) | 150–199 (borderline) | 200–499 (high) | ≥ 500 (very high)",
        "low_significance": "Not clinically significant.",
        "high_significance": "Hypertriglyceridemia — cardiovascular risk, pancreatitis risk (above 500–1000). Causes: poor diet (sugar, refined carbs, alcohol), obesity, diabetes, hypothyroidism, kidney disease, medications.",
        "critical_high": "> 1000 mg/dL — Acute pancreatitis risk",
        "conditions": ["metabolic syndrome", "pancreatitis", "diabetes", "familial hypertriglyceridemia"],
        "symptoms_associated": ["abdominal pain (pancreatitis)", "xanthomas", "no symptoms at moderate levels"],
        "plain_english": "Blood fats from calories not immediately used. High levels from sugar/alcohol/processed foods increase heart disease and pancreatitis risk.",
    },

    # ─── THYROID FUNCTION ──────────────────────────────────────────────────
    {
        "id": "thyroid_tsh",
        "category": "Thyroid",
        "test": "TSH (Thyroid Stimulating Hormone)",
        "normal_range": "0.4–4.0 mIU/L",
        "low_significance": "Low TSH = overactive thyroid (hyperthyroidism) — Graves' disease, toxic nodular goiter, excessive thyroid medication, early Hashimoto's thyrotoxic phase.",
        "high_significance": "High TSH = underactive thyroid (hypothyroidism) — Hashimoto's thyroiditis (most common), thyroid removal, radioiodine treatment, iodine deficiency, certain medications (lithium, amiodarone).",
        "critical_low": "< 0.01 mIU/L — Severe hyperthyroidism (thyroid storm risk)",
        "critical_high": "> 10 mIU/L — Significant hypothyroidism",
        "conditions": ["hypothyroidism", "hyperthyroidism", "Hashimoto's thyroiditis", "Graves' disease"],
        "symptoms_associated": ["fatigue", "weight changes", "temperature sensitivity", "hair loss", "heart palpitations", "anxiety", "constipation", "dry skin", "brain fog", "irregular periods"],
        "plain_english": "TSH is the master thyroid control hormone — it's inverse to thyroid function. High TSH = low thyroid; low TSH = overactive thyroid. Most sensitive screening test.",
    },
    {
        "id": "thyroid_free_t4",
        "category": "Thyroid",
        "test": "Free T4 (Free Thyroxine)",
        "normal_range": "0.8–1.8 ng/dL",
        "low_significance": "Hypothyroidism — when combined with high TSH confirms primary hypothyroidism.",
        "high_significance": "Hyperthyroidism — when combined with low TSH confirms primary hyperthyroidism.",
        "conditions": ["hypothyroidism", "hyperthyroidism", "pituitary disease"],
        "symptoms_associated": ["fatigue", "weight gain/loss", "cold/heat intolerance", "hair loss"],
        "plain_english": "The active form of thyroid hormone circulating freely in blood. Confirms TSH findings and helps distinguish primary from secondary thyroid disease.",
    },
    {
        "id": "thyroid_free_t3",
        "category": "Thyroid",
        "test": "Free T3 (Triiodothyronine)",
        "normal_range": "2.3–4.1 pg/mL",
        "low_significance": "Severe hypothyroidism, euthyroid sick syndrome (in hospitalized patients).",
        "high_significance": "Hyperthyroidism, T3 toxicosis.",
        "conditions": ["hyperthyroidism", "T3 toxicosis"],
        "symptoms_associated": ["heat intolerance", "rapid heartbeat", "anxiety", "tremor", "weight loss"],
        "plain_english": "The most metabolically active thyroid hormone. Useful when TSH is suppressed but T4 is normal — may reveal T3 toxicosis.",
    },

    # ─── DIABETES MARKERS ────────────────────────────────────────────────
    {
        "id": "diabetes_hba1c",
        "category": "Diabetes",
        "test": "HbA1c (Hemoglobin A1c / Glycated Hemoglobin)",
        "normal_range": "< 5.7% (normal) | 5.7–6.4% (prediabetes) | ≥ 6.5% (diabetes)",
        "low_significance": "Not clinically significant (unless < 4% suggesting hemolytic anemia or blood transfusion).",
        "high_significance": "Diabetes management: < 7% is target for most; < 8% for elderly or complex patients. Each 1% drop in A1c reduces complications by ~21%. > 10% = poorly controlled diabetes.",
        "conditions": ["type 2 diabetes", "prediabetes", "type 1 diabetes", "gestational diabetes"],
        "symptoms_associated": ["frequent urination", "excessive thirst", "blurred vision", "slow healing", "fatigue", "frequent infections"],
        "plain_english": "The 3-month average blood sugar — red cells live ~3 months and sugar sticks to them. The most important diabetes management test. Can't be falsely manipulated day-to-day like fasting glucose.",
    },

    # ─── INFLAMMATORY MARKERS ─────────────────────────────────────────────
    {
        "id": "inflammatory_crp",
        "category": "Inflammatory Markers",
        "test": "C-Reactive Protein (CRP)",
        "normal_range": "< 1.0 mg/L (low risk) | 1–3 mg/L (moderate CV risk) | > 3 mg/L (high inflammation)",
        "low_significance": "Not clinically significant.",
        "high_significance": "Acute phase reactant — rises rapidly with infection, inflammation, tissue damage. Very high (> 100 mg/L) suggests bacterial infection or severe inflammation. hs-CRP (high sensitivity) used for cardiovascular risk when < 10 mg/L.",
        "critical_high": "> 200 mg/L — Severe bacterial infection, sepsis",
        "conditions": ["infection", "autoimmune disease", "IBD", "cardiovascular disease risk", "rheumatoid arthritis"],
        "symptoms_associated": ["fever", "joint pain", "fatigue", "chest pain"],
        "plain_english": "A sensitive inflammation marker that rises within hours of infection or injury. The hs-CRP version predicts heart attack risk even at low levels.",
    },
    {
        "id": "inflammatory_esr",
        "category": "Inflammatory Markers",
        "test": "ESR (Erythrocyte Sedimentation Rate)",
        "normal_range": "Men: < 15 mm/hr | Women: < 20 mm/hr (varies with age)",
        "low_significance": "Not clinically significant.",
        "high_significance": "Nonspecific chronic inflammation marker — infection, autoimmune disease (RA, lupus, polymyalgia rheumatica), cancer, anemia, kidney disease. Rises and falls slower than CRP.",
        "conditions": ["RA", "lupus", "polymyalgia rheumatica", "cancer", "chronic infection"],
        "symptoms_associated": ["joint pain", "stiffness", "fatigue", "fever", "weight loss"],
        "plain_english": "Measures how fast red cells settle — inflammation makes blood proteins clump cells together, speeding settlement. Useful for monitoring chronic inflammatory conditions.",
    },
    {
        "id": "inflammatory_ferritin",
        "category": "Inflammatory Markers/Iron",
        "test": "Ferritin",
        "normal_range": "Men: 24–336 ng/mL | Women: 11–307 ng/mL",
        "low_significance": "Iron deficiency — ferritin < 12 ng/mL confirms iron deficiency anemia even with normal hemoglobin (depleted stores). Causes: blood loss, poor absorption, inadequate intake.",
        "high_significance": "Iron overload (hemochromatosis), acute phase reaction (infection, inflammation, liver disease, cancer — ferritin is an acute phase protein). HFE gene mutations cause hereditary hemochromatosis.",
        "critical_low": "< 10 ng/mL — Iron depletion",
        "critical_high": "> 1000 ng/mL — Hemochromatosis or severe inflammation",
        "conditions": ["iron deficiency anemia", "hemochromatosis", "liver disease", "Still's disease"],
        "symptoms_associated": ["fatigue", "hair loss", "cold intolerance", "restless legs", "heart palpitations", "joint pain"],
        "plain_english": "The iron storage protein — the best test for iron deficiency. Low ferritin means empty iron stores; very high may indicate hemochromatosis (iron overload) or inflammation.",
    },

    # ─── CARDIAC MARKERS ─────────────────────────────────────────────────
    {
        "id": "cardiac_troponin",
        "category": "Cardiac",
        "test": "Troponin I / Troponin T (High-Sensitivity)",
        "normal_range": "hs-Troponin I: < 19–52 pg/mL (sex-specific) | hs-Troponin T: < 14 pg/mL",
        "low_significance": "Not clinically significant.",
        "high_significance": "Heart muscle damage. Even slight elevations are significant. Rising pattern (serial measurements) confirms myocardial infarction. Also elevated in PE, myocarditis, heart failure, severe infections, kidney disease.",
        "critical_high": "Any elevation above 99th percentile requires urgent evaluation",
        "conditions": ["myocardial infarction", "NSTEMI", "myocarditis", "pulmonary embolism", "heart failure"],
        "symptoms_associated": ["chest pain", "chest pressure", "jaw pain", "left arm pain", "shortness of breath", "sweating", "nausea"],
        "plain_english": "The most specific heart damage marker. Elevated troponin means heart muscle cells have been injured and are leaking this protein. The gold standard for diagnosing heart attacks.",
    },
    {
        "id": "cardiac_bnp",
        "category": "Cardiac",
        "test": "BNP / NT-proBNP (B-type Natriuretic Peptide)",
        "normal_range": "BNP: < 100 pg/mL | NT-proBNP: < 125 pg/mL (age-adjusted)",
        "low_significance": "Helps rule out heart failure (NPV > 95% when < 100 pg/mL).",
        "high_significance": "Heart failure with reduced or preserved ejection fraction, cardiac overload, pulmonary hypertension, kidney disease. Used for diagnosis and monitoring of heart failure.",
        "critical_high": "BNP > 400 pg/mL — Heart failure likely",
        "conditions": ["congestive heart failure", "cardiac overload", "pulmonary hypertension"],
        "symptoms_associated": ["shortness of breath", "leg swelling", "orthopnea", "fatigue", "reduced exercise tolerance"],
        "plain_english": "Released by heart cells under pressure/stretch. The most important blood test for diagnosing and monitoring heart failure severity.",
    },

    # ─── VITAMINS & NUTRIENTS ─────────────────────────────────────────────
    {
        "id": "vitamin_b12",
        "category": "Vitamins",
        "test": "Vitamin B12 (Cobalamin)",
        "normal_range": "200–900 pg/mL",
        "low_significance": "B12 deficiency — pernicious anemia (loss of intrinsic factor), strict veganism/vegetarianism, malabsorption (celiac, IBD, gastric surgery), metformin use, PPIs (long-term), older adults.",
        "high_significance": "Liver disease, polycythemia vera, CML, some solid tumors (paradoxically elevated despite deficiency in function).",
        "critical_low": "< 150 pg/mL — Neurological damage risk",
        "conditions": ["pernicious anemia", "macrocytic anemia", "peripheral neuropathy", "veganism", "celiac disease"],
        "symptoms_associated": ["fatigue", "numbness and tingling (hands/feet)", "memory problems", "balance issues", "mouth sores", "glossitis", "depression", "pale/yellow skin"],
        "plain_english": "Essential for nerve function and red blood cell production. Deficiency progresses from fatigue to permanent nerve damage. Strict vegans are especially at risk.",
    },
    {
        "id": "vitamin_d",
        "category": "Vitamins",
        "test": "Vitamin D (25-hydroxyvitamin D)",
        "normal_range": "< 12 ng/mL (deficient) | 12–20 ng/mL (insufficient) | 20–50 ng/mL (sufficient) | > 50 ng/mL (potentially harmful)",
        "low_significance": "Deficiency — bone disease (osteoporosis, rickets, osteomalacia), muscle weakness, immune dysfunction, depression. Risk factors: limited sun, dark skin, obesity, kidney/liver disease, malabsorption.",
        "high_significance": "Vitamin D toxicity — hypercalcemia, kidney stones, confusion. Usually from excessive supplementation (> 4000 IU/day long-term).",
        "critical_low": "< 10 ng/mL — Severe deficiency with risk of osteomalacia",
        "critical_high": "> 150 ng/mL — Toxicity with hypercalcemia",
        "conditions": ["osteoporosis", "osteomalacia", "rickets", "immune dysfunction", "depression"],
        "symptoms_associated": ["bone pain", "muscle weakness", "fatigue", "depression", "frequent illness", "hair loss"],
        "plain_english": "The 'sunshine vitamin.' Deficiency is extremely common — especially in northern latitudes, dark-skinned people, and those who avoid sun. Critical for bones, immunity, and mood.",
    },
    {
        "id": "vitamin_folate",
        "category": "Vitamins",
        "test": "Folate (Folic Acid / Vitamin B9)",
        "normal_range": "> 2.0 ng/mL (serum) | > 140 ng/mL (RBC folate)",
        "low_significance": "Folate deficiency — macrocytic anemia, neural tube defects (critical in pregnancy), megaloblastic changes. Causes: poor diet, alcohol, malabsorption, medications (methotrexate, phenytoin).",
        "high_significance": "Not clinically significant.",
        "conditions": ["megaloblastic anemia", "neural tube defects", "alcohol use disorder", "malabsorption"],
        "symptoms_associated": ["fatigue", "mouth sores", "cognitive issues", "pallor"],
        "plain_english": "Essential for DNA synthesis and cell division — especially critical in pregnancy to prevent birth defects. Often supplemented in prenatal vitamins.",
    },

    # ─── IRON STUDIES ─────────────────────────────────────────────────────
    {
        "id": "iron_serum",
        "category": "Iron Studies",
        "test": "Serum Iron",
        "normal_range": "Men: 65–175 µg/dL | Women: 50–170 µg/dL",
        "low_significance": "Iron deficiency, anemia of chronic disease, malabsorption.",
        "high_significance": "Hemochromatosis, iron supplementation excess, liver disease, hemolytic anemia.",
        "conditions": ["iron deficiency anemia", "hemochromatosis"],
        "symptoms_associated": ["fatigue", "hair loss", "weakness"],
        "plain_english": "The amount of iron currently circulating in blood. Must be interpreted with TIBC and ferritin for the full iron picture.",
    },
    {
        "id": "iron_tibc",
        "category": "Iron Studies",
        "test": "TIBC (Total Iron Binding Capacity)",
        "normal_range": "250–370 µg/dL",
        "low_significance": "Hemochromatosis, anemia of chronic disease, malnutrition, liver disease.",
        "high_significance": "Iron deficiency anemia (body upregulates transferrin to capture more iron), pregnancy.",
        "conditions": ["iron deficiency", "hemochromatosis"],
        "symptoms_associated": ["fatigue", "weakness"],
        "plain_english": "Measures how much iron blood could carry if fully loaded. High TIBC with low iron confirms iron deficiency.",
    },
    {
        "id": "iron_transferrin_sat",
        "category": "Iron Studies",
        "test": "Transferrin Saturation",
        "normal_range": "20–50%",
        "low_significance": "Iron deficiency — saturation < 20%.",
        "high_significance": "Hemochromatosis — saturation > 45% (men) or > 40% (women) is the screening threshold for hereditary hemochromatosis.",
        "critical_high": "> 70% — Significant iron overload",
        "conditions": ["hemochromatosis", "iron deficiency"],
        "symptoms_associated": ["fatigue", "joint pain", "liver disease", "diabetes (in hemochromatosis)"],
        "plain_english": "The percentage of iron transport protein (transferrin) currently loaded with iron. High saturation is the main hemochromatosis screening signal.",
    },

    # ─── HORMONE TESTS ────────────────────────────────────────────────────
    {
        "id": "hormone_testosterone",
        "category": "Hormones",
        "test": "Total Testosterone",
        "normal_range": "Men: 300–1000 ng/dL | Women: 15–70 ng/dL",
        "low_significance": "Hypogonadism — primary (testicular failure) or secondary (pituitary/hypothalamic). Causes in men: aging, obesity, chronic illness, medications (opioids, steroids), radiation.",
        "high_significance": "Polycystic ovary syndrome (PCOS) in women, anabolic steroid use, adrenal tumors, Leydig cell tumors.",
        "conditions": ["hypogonadism", "PCOS", "adrenal disorders", "anabolic steroid use"],
        "symptoms_associated": ["low libido", "fatigue", "depression", "erectile dysfunction", "muscle loss", "hot flashes", "infertility", "hair loss", "irregular periods (women)", "acne (women)"],
        "plain_english": "The primary male sex hormone (also important in women). Low testosterone causes fatigue, low libido, and muscle loss. High levels in women suggest PCOS.",
    },
    {
        "id": "hormone_cortisol",
        "category": "Hormones",
        "test": "Cortisol (8 AM serum)",
        "normal_range": "6–23 µg/dL (8 AM) | < 5 µg/dL suggests adrenal insufficiency",
        "low_significance": "Adrenal insufficiency — primary (Addison's disease) or secondary (pituitary failure). Medical emergency if severely low with symptoms.",
        "high_significance": "Cushing's syndrome — pituitary adenoma (Cushing's disease), adrenal adenoma, ectopic ACTH, exogenous steroid use. Causes central obesity, hypertension, diabetes, osteoporosis.",
        "conditions": ["Addison's disease", "Cushing's syndrome", "adrenal tumor", "chronic stress"],
        "symptoms_associated": ["weight changes", "fatigue", "muscle weakness", "blood pressure changes", "stretch marks", "buffalo hump", "moon face", "frequent infections"],
        "plain_english": "The primary stress hormone made by adrenal glands. Too little causes Addison's disease (life-threatening); too much causes Cushing's syndrome with characteristic body fat distribution.",
    },

    # ─── URINALYSIS ──────────────────────────────────────────────────────
    {
        "id": "ua_protein",
        "category": "Urinalysis",
        "test": "Urine Protein / Proteinuria",
        "normal_range": "< 150 mg/day | Urine dipstick: Negative",
        "low_significance": "Not clinically significant.",
        "high_significance": "Kidney disease — diabetic nephropathy, hypertensive nephropathy, glomerulonephritis, nephrotic syndrome. Albumin-to-creatinine ratio (ACR) > 30 mg/g is microalbuminuria.",
        "critical_high": "> 3.5 g/day — Nephrotic syndrome",
        "conditions": ["diabetic nephropathy", "hypertensive nephropathy", "glomerulonephritis", "lupus nephritis"],
        "symptoms_associated": ["foamy urine", "swelling", "hypertension"],
        "plain_english": "Protein shouldn't spill into urine. Persistently elevated urine protein indicates kidney damage — an early warning in diabetes and hypertension.",
    },

    # ─── SYMPTOM-CONDITION CORRELATIONS ─────────────────────────────────
    {
        "id": "symptom_fatigue",
        "category": "Symptom Guide",
        "test": "Fatigue — Common Causes and Tests",
        "description": "Fatigue is a nonspecific symptom with many causes. Common underlying conditions: anemia (check CBC, iron studies), hypothyroidism (check TSH), diabetes (check HbA1c, glucose), depression, sleep apnea, chronic kidney disease (check BMP), liver disease (check LFTs), vitamin D deficiency, B12 deficiency, heart failure (check BNP), adrenal insufficiency (check morning cortisol), celiac disease, chronic infections (HIV, Lyme).",
        "recommended_tests": ["CBC", "CMP", "TSH", "HbA1c", "Vitamin D", "B12", "Ferritin", "Cortisol AM"],
        "conditions": ["anemia", "hypothyroidism", "diabetes", "depression", "sleep apnea", "CKD", "liver disease"],
        "plain_english": "Fatigue needs targeted investigation. A basic panel (CBC, CMP, TSH, HbA1c, B12, Vitamin D, ferritin) catches the most common reversible causes.",
    },
    {
        "id": "symptom_weight_gain",
        "category": "Symptom Guide",
        "test": "Unexplained Weight Gain — Common Causes",
        "description": "Hypothyroidism, Cushing's syndrome, diabetes/insulin resistance, polycystic ovary syndrome (PCOS), heart failure (fluid retention), medications (antidepressants, steroids, antipsychotics), depression, sleep apnea, menopause.",
        "recommended_tests": ["TSH", "Free T4", "Cortisol AM", "HbA1c", "Fasting Glucose", "Testosterone (women)", "FSH/LH"],
        "conditions": ["hypothyroidism", "Cushing's syndrome", "diabetes", "PCOS", "heart failure"],
        "plain_english": "Unexplained weight gain often has a hormonal cause — hypothyroidism and Cushing's syndrome are most commonly missed.",
    },
    {
        "id": "symptom_joint_pain",
        "category": "Symptom Guide",
        "test": "Joint Pain — Relevant Lab Tests",
        "description": "Rheumatoid arthritis (RA factor, anti-CCP), gout (uric acid), lupus (ANA, anti-dsDNA), hypothyroidism (TSH), Lyme disease (Lyme Ab), osteoarthritis (no specific blood test), reactive arthritis, psoriatic arthritis.",
        "recommended_tests": ["Uric Acid", "CRP", "ESR", "RF", "Anti-CCP", "ANA", "TSH", "CBC", "CMP"],
        "conditions": ["gout", "RA", "lupus", "osteoarthritis", "Lyme disease", "pseudogout"],
        "plain_english": "Joint pain workup depends on pattern: sudden single-joint (think gout), multiple joints/morning stiffness (think RA or lupus), with rash (think Lyme or lupus).",
    },
    {
        "id": "condition_metabolic_syndrome",
        "category": "Condition Guide",
        "test": "Metabolic Syndrome — Lab Criteria",
        "description": "Diagnosed with 3 of 5 criteria: Waist circumference ≥ 40\" (men) / 35\" (women), Triglycerides ≥ 150 mg/dL, HDL < 40 (men) / 50 (women) mg/dL, Blood pressure ≥ 130/85, Fasting glucose ≥ 100 mg/dL. Raises risk for type 2 diabetes, cardiovascular disease, NAFLD, PCOS.",
        "conditions": ["type 2 diabetes risk", "cardiovascular disease", "NAFLD", "PCOS"],
        "symptoms_associated": ["abdominal obesity", "fatigue", "darkened skin patches (acanthosis)"],
        "plain_english": "A cluster of conditions that dramatically increase risk for diabetes and heart disease. Treatment focuses on lifestyle modification — losing 5–10% body weight improves all 5 markers.",
    },
]


def get_all_documents():
    """Return all knowledge base documents as text chunks for ChromaDB."""
    docs = []
    ids = []
    metadatas = []

    for item in MEDICAL_KNOWLEDGE:
        # Build comprehensive text for each entry
        parts = [f"Test: {item.get('test', item.get('description', ''))}", f"Category: {item.get('category', '')}"]

        if "normal_range" in item:
            parts.append(f"Normal Range: {item['normal_range']}")
        if "low_significance" in item:
            parts.append(f"Low/Decreased: {item['low_significance']}")
        if "high_significance" in item:
            parts.append(f"High/Elevated: {item['high_significance']}")
        if "critical_low" in item:
            parts.append(f"Critical Low: {item['critical_low']}")
        if "critical_high" in item:
            parts.append(f"Critical High: {item['critical_high']}")
        if "conditions" in item:
            parts.append(f"Associated conditions: {', '.join(item['conditions'])}")
        if "symptoms_associated" in item:
            parts.append(f"Symptoms: {', '.join(item['symptoms_associated'])}")
        if "recommended_tests" in item:
            parts.append(f"Recommended tests: {', '.join(item['recommended_tests'])}")
        if "plain_english" in item:
            parts.append(f"Patient explanation: {item['plain_english']}")
        if "description" in item:
            parts.append(f"Details: {item['description']}")

        docs.append("\n".join(parts))
        ids.append(item["id"])
        metadatas.append({
            "category": item.get("category", ""),
            "test": item.get("test", item.get("description", "")),
        })

    return docs, ids, metadatas
