"use client";

import { useEffect, useState } from "react";
import { use } from "react";
import { FlaskConical, CheckCircle, AlertTriangle, AlertCircle, Printer, Shield } from "lucide-react";

interface LabValue {
  test_name: string;
  value: string;
  unit: string;
  reference_range: string;
  status: string;
  category: string;
  plain_english_explanation: string;
}

interface SharedReport {
  patient_name: string;
  report_date: string;
  lab_values: LabValue[];
  ai_summary: string;
  expires_at: string;
}

const statusConfig: Record<string, { icon: typeof CheckCircle; color: string; bg: string; label: string }> = {
  normal: { icon: CheckCircle, color: "text-emerald-700", bg: "bg-emerald-50 border-emerald-200", label: "Normal" },
  low: { icon: AlertTriangle, color: "text-amber-700", bg: "bg-amber-50 border-amber-200", label: "Low" },
  high: { icon: AlertTriangle, color: "text-amber-700", bg: "bg-amber-50 border-amber-200", label: "High" },
  critical_low: { icon: AlertCircle, color: "text-red-700", bg: "bg-red-50 border-red-200", label: "Critical Low" },
  critical_high: { icon: AlertCircle, color: "text-red-700", bg: "bg-red-50 border-red-200", label: "Critical High" },
};

export default function SharedReportPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = use(params);
  const [report, setReport] = useState<SharedReport | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch(`/shared/${token}`)
      .then((r) => {
        if (!r.ok) throw new Error("Report not found or link has expired.");
        return r.json();
      })
      .then(setReport)
      .catch((e) => setError(e.message))
      .finally(() => setLoading(false));
  }, [token]);

  if (loading) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center">
        <div className="text-center">
          <div className="w-12 h-12 border-4 border-blue-600 border-t-transparent rounded-full animate-spin mx-auto mb-4" />
          <p className="text-slate-500">Loading shared report...</p>
        </div>
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center p-4">
        <div className="bg-white border border-red-200 rounded-2xl p-8 max-w-md text-center">
          <AlertCircle className="w-12 h-12 text-red-400 mx-auto mb-4" />
          <h2 className="text-xl font-bold text-slate-900 mb-2">Report Unavailable</h2>
          <p className="text-slate-500">{error || "This report link is invalid or has expired."}</p>
        </div>
      </div>
    );
  }

  const groupedValues = report.lab_values.reduce<Record<string, LabValue[]>>((acc, v) => {
    const cat = v.category || "Other";
    if (!acc[cat]) acc[cat] = [];
    acc[cat].push(v);
    return acc;
  }, {});

  const critical = report.lab_values.filter((v) => v.status?.includes("critical"));
  const abnormal = report.lab_values.filter((v) => ["low", "high"].includes(v.status));
  const normal = report.lab_values.filter((v) => v.status === "normal");

  return (
    <div className="min-h-screen bg-slate-50 print:bg-white">
      {/* Print header */}
      <div className="hidden print:block text-center py-6 border-b border-slate-200 mb-6">
        <p className="text-sm text-slate-400">Generated by MedLab AI · medlabai.com</p>
      </div>

      {/* Top bar */}
      <div className="bg-white border-b border-slate-200 print:hidden">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-gradient-to-br from-blue-600 to-indigo-700 rounded-lg flex items-center justify-center">
              <FlaskConical className="w-4 h-4 text-white" />
            </div>
            <span className="font-bold text-slate-900">MedLab AI</span>
          </div>
          <button
            onClick={() => window.print()}
            className="flex items-center gap-2 text-sm font-medium text-slate-600 hover:text-blue-600 border border-slate-200 hover:border-blue-300 px-4 py-2 rounded-lg transition-colors"
          >
            <Printer className="w-4 h-4" />
            Print / Save PDF
          </button>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 py-8 space-y-6">
        {/* Header */}
        <div className="bg-gradient-to-br from-blue-700 to-indigo-700 rounded-2xl p-8 text-white print:bg-blue-700">
          <p className="text-blue-200 text-sm font-medium mb-2">Shared Lab Report · MedLab AI</p>
          <h1 className="text-2xl font-bold mb-1">{report.patient_name || "Lab Results"}</h1>
          <p className="text-blue-200 text-sm">
            Report date: {report.report_date ? new Date(report.report_date).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }) : "N/A"}
          </p>
          <div className="flex items-center gap-2 mt-4 text-blue-200 text-xs">
            <Shield className="w-3.5 h-3.5" />
            This link expires {new Date(report.expires_at).toLocaleDateString()}
          </div>
        </div>

        {/* Summary stats */}
        <div className="grid grid-cols-3 gap-4">
          {[
            { label: "Normal", count: normal.length, color: "bg-emerald-50 text-emerald-700 border-emerald-200" },
            { label: "Abnormal", count: abnormal.length, color: "bg-amber-50 text-amber-700 border-amber-200" },
            { label: "Critical", count: critical.length, color: "bg-red-50 text-red-700 border-red-200" },
          ].map((s) => (
            <div key={s.label} className={`border rounded-xl p-4 text-center ${s.color}`}>
              <p className="text-2xl font-bold">{s.count}</p>
              <p className="text-sm font-medium">{s.label}</p>
            </div>
          ))}
        </div>

        {/* Critical alert */}
        {critical.length > 0 && (
          <div className="bg-red-50 border border-red-200 rounded-xl p-4 flex items-start gap-3">
            <AlertCircle className="w-5 h-5 text-red-500 mt-0.5 flex-shrink-0" />
            <div>
              <p className="font-semibold text-red-800">{critical.length} critical value{critical.length > 1 ? "s" : ""} require immediate attention</p>
              <p className="text-red-700 text-sm mt-0.5">Please consult your healthcare provider as soon as possible.</p>
            </div>
          </div>
        )}

        {/* AI Summary */}
        {report.ai_summary && (
          <div className="bg-white border border-slate-200 rounded-2xl p-6">
            <h2 className="font-bold text-slate-900 text-lg mb-4 flex items-center gap-2">
              <div className="w-6 h-6 bg-blue-100 rounded-lg flex items-center justify-center">
                <FlaskConical className="w-3.5 h-3.5 text-blue-600" />
              </div>
              AI Summary
            </h2>
            <div className="prose prose-sm max-w-none text-slate-700 leading-relaxed whitespace-pre-wrap">
              {report.ai_summary.slice(0, 1500)}{report.ai_summary.length > 1500 ? "..." : ""}
            </div>
          </div>
        )}

        {/* Lab values by category */}
        {Object.entries(groupedValues).map(([category, values]) => (
          <div key={category} className="bg-white border border-slate-200 rounded-2xl overflow-hidden">
            <div className="px-6 py-4 bg-slate-50 border-b border-slate-100">
              <h3 className="font-bold text-slate-800">{category}</h3>
            </div>
            <div className="divide-y divide-slate-100">
              {values.map((v, i) => {
                const cfg = statusConfig[v.status] || statusConfig.normal;
                const Icon = cfg.icon;
                return (
                  <div key={i} className="px-6 py-4">
                    <div className="flex items-start justify-between gap-4 mb-2">
                      <div className="flex-1">
                        <div className="flex items-center gap-2 mb-1">
                          <p className="font-semibold text-slate-900">{v.test_name}</p>
                          <span className={`inline-flex items-center gap-1 text-xs font-medium px-2 py-0.5 rounded-full border ${cfg.bg} ${cfg.color}`}>
                            <Icon className="w-3 h-3" />
                            {cfg.label}
                          </span>
                        </div>
                        <p className="text-xs text-slate-400">Reference: {v.reference_range}</p>
                      </div>
                      <div className="text-right flex-shrink-0">
                        <p className={`text-xl font-bold ${cfg.color}`}>{v.value}</p>
                        <p className="text-xs text-slate-400">{v.unit}</p>
                      </div>
                    </div>
                    {v.plain_english_explanation && (
                      <p className="text-sm text-slate-600 bg-slate-50 rounded-lg px-3 py-2 mt-2 leading-relaxed">
                        {v.plain_english_explanation}
                      </p>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        ))}

        {/* Disclaimer */}
        <div className="bg-amber-50 border border-amber-200 rounded-xl p-4">
          <p className="text-xs text-amber-700 text-center">
            This report was generated by MedLab AI for educational purposes only. It is not a medical diagnosis.
            Always consult a licensed healthcare provider for medical decisions.
          </p>
        </div>
      </div>
    </div>
  );
}
